Repository b4mad/op1st-emea-b4mad, pull requests merged in 2023-05, with the labels that each got.

#9 ✨🌼 add nmstate operator as an argocd app
  manifests/applications/kustomization.yaml
  manifests/applications/nmstate-operator.yaml
  manifests/applications/nmstate.yaml
  manifests/applications/nmstate/kustomization.yaml
  manifests/applications/nmstate/nmstate.yaml
Labels: size/M, approved

#10 remove cookie secret
  manifests/applications/prow/branchprotector.yaml
Labels: size/XS, approved

#8 :bug: 🧪 update test for cert-manager, ingress, route
  tests/b4mad-racing-tls-route.yaml
Labels: size/S

#11 bump grafana operator to rc2
  manifests/environments/phobos/grafana-operator/README.md
  manifests/environments/phobos/grafana-operator/grafana-operator/README.md
  manifests/environments/phobos/grafana-operator/grafana-operator/base/crds.yaml
  manifests/environments/phobos/grafana-operator/grafana-operator/base/kustomization.yaml
Labels: size/M

#12 add phobos app
  manifests/applications/environment-phobos.yaml
  manifests/applications/kustomization.yaml
  manifests/environments/phobos/kustomization.yaml
  manifests/environments/phobos/lvm-storage/lvm-cluster.yaml
Labels: size/S, approved

#14 lvm storage phobos
  manifests/environments/phobos/lvm-storage/lvm-cluster.yaml
Labels: size/S

#13 made cert-manager-operator part of each environment, its a platform service, not an application
  manifests/applications/cert-manager-operator/environments/phobos/kustomization.yaml
  manifests/applications/environment-nostromo.yaml
  manifests/applications/kustomization.yaml
  manifests/applications/prow/namespace.yaml
  manifests/components/openshift-gitops-integration/bitnami-sealedsecrets-admin.yaml
  manifests/components/openshift-gitops-integration/kustomization.yaml
  manifests/environments/nostromo/cert-manager-operator/cloudflare-b4mad-racing-dns01-solver.yaml
  manifests/environments/nostromo/cert-manager-operator/cluster-cert-manager.yaml
  manifests/environments/nostromo/cert-manager-operator/google-clouddns-dns01-solver.yaml
  manifests/environments/nostromo/cert-manager-operator/kustomization.yaml
  manifests/environments/nostromo/cert-manager-operator/letsencrypt-cluster-issuer.yaml
  manifests/environments/nostromo/kustomization.yaml
  manifests/environments/nostromo/openshift-gitops/argocd-configs/envs
  manifests/environments/nostromo/openshift-gitops/argocd-configs/policy.csv
  manifests/environments/nostromo/openshift-gitops/argocd-configs/policy.default
  manifests/environments/nostromo/openshift-gitops/argocd-openshift-gitops.yaml
  manifests/environments/nostromo/openshift-gitops/bitnami-sealedsecret_rbac.yaml
  manifests/environments/nostromo/openshift-gitops/kustomization.yaml
  manifests/environments/phobos/cert-manager-operator/cloudflare-b4mad-racing-dns01-solver.yaml
  manifests/environments/phobos/cert-manager-operator/cluster-cert-manager.yaml
  manifests/environments/phobos/cert-manager-operator/google-clouddns-dns01-solver.yaml
  manifests/environments/phobos/cert-manager-operator/kustomization.yaml
  manifests/environments/phobos/cert-manager-operator/letsencrypt-cluster-issuer.yaml
  manifests/environments/phobos/kustomization.yaml
  manifests/environments/phobos/openshift-gitops-integration.yaml
Labels: size/L, do-not-merge/hold

#17 🗞️ add app sync status icons to readme
  README.md
Labels: size/XS

#19 🛟 use ServerSideApply for the ArgoCD Application "environment-phobos"
  manifests/applications/environment-phobos.yaml
Labels: size/XS, approved

#20 🥳 add Peribolos-as-a-Service
  manifests/applications/kustomization.yaml
  manifests/applications/peribolos.yaml
  manifests/applications/peribolos/.transformers.yaml
  manifests/applications/peribolos/controller/.transformers.yaml
  manifests/applications/peribolos/controller/deployment.yaml
  manifests/applications/peribolos/controller/kustomization.yaml
  manifests/applications/peribolos/controller/role.yaml
  manifests/applications/peribolos/controller/rolebinding.yaml
  manifests/applications/peribolos/controller/route.yaml
  manifests/applications/peribolos/controller/service.yaml
  manifests/applications/peribolos/controller/serviceaccount.yaml
  manifests/applications/peribolos/controller/servicemonitor.yaml
  manifests/applications/peribolos/ingress.yaml
  manifests/applications/peribolos/kustomization.yaml
  manifests/applications/peribolos/monitoring/kustomization.yaml
  manifests/applications/peribolos/monitoring/prometheusrule.yaml
  manifests/applications/peribolos/namespace.yaml
  manifests/applications/peribolos/secrets/peribolos-controller.yaml
  manifests/applications/peribolos/tasks/.transformers.yaml
  manifests/applications/peribolos/tasks/dump-config.yaml
  manifests/applications/peribolos/tasks/kustomization.yaml
  manifests/applications/peribolos/tasks/run.yaml
Labels: approved, size/XL

#22 grafana operator rc3
  manifests/environments/phobos/grafana-operator/README.md
  manifests/environments/phobos/grafana-operator/grafana-operator/README.md
  manifests/environments/phobos/grafana-operator/grafana-operator/base/crds.yaml
  manifests/environments/phobos/grafana-operator/grafana-operator/base/deployment.yaml
  manifests/environments/phobos/grafana-operator/grafana-operator/base/kustomization.yaml
  manifests/environments/phobos/grafana-operator/grafana-operator/base/service.yaml
Labels: size/L, approved

#23 add b4mad-racing argocd application
  manifests/applications/b4mad-racing.yaml
  manifests/applications/kustomization.yaml
Labels: size/S, approved
