Repository b4mad/op1st-emea-b4mad, pull requests merged in 2023-09, with the labels that each got.

#37 build: automatic update of prow
  manifests/applications/prow/kustomization.yaml
Labels: size/S

#39 Add jcapiitao as reviewer
  manifests/environments/okd/cluster-01/OWNERS
Labels: size/XS, approved

#40 feat(argocd-image-updater): add the argocd-image-updater app
  manifests/applications/argocd-image-updater.yaml
  manifests/applications/argocd-image-updater/configmaps.yaml
  manifests/applications/argocd-image-updater/deployment.yaml
  manifests/applications/argocd-image-updater/kustomization.yaml
  manifests/applications/argocd-image-updater/service.yaml
  manifests/applications/argocd-image-updater/service_account.yaml
  manifests/applications/argocd-image-updater/service_monitors.yaml
  manifests/applications/kustomization.yaml
Labels: size/L

#42 build: automatic update of prow
  manifests/applications/prow/kustomization.yaml
Labels: size/S, approved
